### ISSUE TITLE
顶部导航上【关注我们】的下拉被隐藏了

### ISSUE THREAD

**Issue by dddreee** [docschina/docschina.org#11]
![image](https://user-images.githubusercontent.com/11844788/42747123-8c551812-890d-11e8-8460-3e3755732ea0.png)

**Comment by dear-lizhihua** [comment]
iview 的问题，不知道什么时候开始就出错了，我修复下吧……

**Comment by dear-lizhihua** [comment]
已修复

**Comment by ShengWeiJNU** [comment]
![image](https://user-images.githubusercontent.com/29245969/53462072-78971100-3a7d-11e9-9228-31834c1860a7.png)

刚才打开顶部导航栏下拉列表还是被遮挡的；而且hover“原创内容”和“关注我们”之一，两个折叠icon同时切换状态
