### ISSUE TITLE
网站界面改版了？

### ISSUE THREAD

**Issue by fengfengchen** [docschina/docschina.org#18]
新版的好亮，对眼睛不友好，尤其是分类标签，很难看出是什么文字

**Comment by QC-L** [comment]
是，颜色我晚些调整下，有什么建议嘛？

**Comment by fengfengchen** [comment]
从我的使用体验来说：
1. 导航的分类标签在未选中状态下颜色较浅，刚开始以为是字体颜色的问题，才发现是opcity的锅，建议去除这个属性。
2. 选项卡也不够醒目，建议选项卡的标题加粗，选项卡的描述文字（.dc-card-item-desc）色度深些，然后选项卡底部的横条（.dc-card-item-footer）背景色深些；
以上仅是我从一个前端人员的角度提出的看法，不当之处还请见谅，另，感谢大佬所做的贡献！

**Comment by QC-L** [comment]
1. opcity 我把其值调大些
2. 标题已加粗，描述文字和横条颜色已加深。

你可以感觉下，不行再调整。

**Comment by fengfengchen** [comment]
1. 不知道是不是我显示器的问题，分类标签识别效果还是比较差，
2. 横条颜色个人感觉有点偏浅
其他看起来都挺好

**Comment by QC-L** [comment]
可能有缓存，强制刷新下
