### ISSUE TITLE
这新版的文档网站也太难用了吧

### ISSUE THREAD

**Issue by Chad97** [docschina/docschina.org#20]
这新版的文档网站也太难用了吧，不让用户看到的全部文档非要隐藏掉滑动？浏览器的滑动条还在只是没什么用，我以为是适配手机端的，发现safari 也挺难用的，锚点没问题 但是为了锚点 让他隐藏然后滑动 有点难受哦~

**Comment by QC-L** [comment]
谢谢建议，是需要内容部分的滚动条？我特意隐藏的..

**Comment by Chad97** [comment]
👍  嘿嘿～ 感谢大佬采纳
 👍 这样子找文档 就方便多了~ 
&emsp; 个人小小小小的建议：其实作为文档网站来讲 没必要吧content部分`position: fixed;`滑动的 让他自然长度就可以了 导航栏的锚点 可以 `position: fixed;` 方便跳转道对应的模块部分，如果是为了突出 footer 部分的友链 QR code 什么的 可以把关键信息做个侧边栏目 `position: fixed;` footer 不那么长就不用一个page 2个滑动条了 。
:octocat: 做的已经挺好的了，大佬别建议 说的有点多 😂

**Comment by QC-L** [comment]
嗯，好的。我看看怎么改~多谢关注~
