### ISSUE TITLE
首页布局提议

### ISSUE THREAD

**Issue by bangquanwu** [docschina/docschina.org#22]
1. 左侧和顶部内容长期固定在视野内，导致正文文档列表内容占比显得逼仄，像这些低频展示功能建议可以折叠，滑动离开视野，或者放到其他二级目录下
2. 双滚动条
3. 文档列表卡片提高可识别度

**Comment by QC-L** [comment]
1. 你发个截图我看下...请截图示意
2. 双滚动条在处理，目前先这样
3. 提高辨识度是指哪方面？没太理解

**Comment by ZY2071** [comment]
新版还不如老版的设计好看，现在难以区分各个板块，卡片的配色也不如从前
